default:
  image: php:8.1-cli

cache:
  paths:
    - vendor/

stages:
  - test-app

before_script:
  # Install git, the php image doesn't have installed
  - apt-get update -yqq
  - apt-get install git -yqq

  # Install mysql driver
  - docker-php-ext-install pdo pdo_mysql

  # Install composer
  - curl -sS https://getcomposer.org/installer | php

  # Install all project dependencies
  - php composer.phar install

  # PHP UNIT
  - curl https://phar.phpunit.de/phpunit-9.5.27.phar --output phpunit-9.5.27.phar
  - chmod +x phpunit-9.5.27.phar
  - mv phpunit-9.5.27.phar /usr/local/bin/phpunit

  # XDebug
  - pecl install xdebug
  - docker-php-ext-enable xdebug

tests:
  stage: test-app
  variables:
    XDEBUG_MODE: coverage
  script: vendor/bin/phpunit --coverage-text
  allow_failure: false